image: node:12

stages:
  - build
  - release

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
  policy: pull

before_script:
  - yarn --frozen-lockfile --production=false || true # Don't blow up when 'yarn' doesn't exist

install:
  stage: build
  script:
    - echo 🐖
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
    policy: pull-push

build:
  stage: build
  script:
    - yarn bundle
  artifacts:
    paths:
      - data/
      - dist/

audit:
  stage: build
  script:
    - yarn audit
  allow_failure: true

storybook:
  stage: build
  script:
    - yarn storybook:build
  artifacts:
    paths:
      - dist-storybook/
  only:
    - develop

test:
  stage: build
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - yarn test --coverage

types:
  stage: build
  script:
    - yarn types

lint:
  stage: build
  script:
    - yarn lint

#relay:
#  stage: build
#  script:
#    # maybe also syncgql
#    - yarn relay --validate

types:
  stage: build
  script:
    - yarn types

madge:
  stage: build
  script:
    - yarn madge

release dev:
  image: ruby
  stage: release
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  only:
    - develop

release prod:
  image: ruby
  stage: release
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PROD_APP --api-key=$HEROKU_PROD_API_KEY
  only:
    - master
